### ISSUE TITLE
Invalid repo in dotnet-releaser.toml

### ISSUE THREAD

**Issue by xoofx** [trmcnealy/Plotly.WPF#1]
Hey,

I noticed that this line is not configured correctly:

https://github.com/trmcnealy/Plotly.WPF/blob/6e9549aafa0a755538e54ce4192638b97a2ffa31/dotnet-releaser.toml#L6

The repo should be the repo name, so `Plotly.WPF` instead:

```
[msbuild]
project = "Plotly.WPF.csproj"
[github]
user = "trmcnealy"
repo = "Plotly.WPF"
```

**Comment by trmcnealy** [comment]
Thank you,  I updated it.
